#
#
#
- name: Install System Packages
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - nginx
    # for htpasswd, if needed
    - apache2-utils

- name: Copy nginx config
  copy:
    content: |
      events {worker_connections  1024;}
      http {
        upstream jenkins {server 127.0.0.1:8080;}
        server {
          listen 80;
          location / {
            proxy_pass http://jenkins;
            proxy_redirect off;
          }
        }
      }
    dest: /etc/nginx/nginx.conf

- name: Enable and restart nginx
  service:
    name: nginx
    enabled: yes
    state: restarted
